font_family Liberation Mono
background_opacity 1.0
foreground         #c7c4c2
background         #0D161D
cursor             #c7c4c2

include /home/shrutip/.config/kitty/Catppuccin-Mocha.conf
shell /bin/zsh
